version: '3.8'

services:
  telegram-bot:
    container_name: maritime-telegram-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - maritime-network
    restart: unless-stopped

networks:
  maritime-network:
    external: true